# Generated by Django 5.0.3 on 2026-03-14 02:37

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], db_index=True, default='LOST', max_length=10)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics & Gadgets'), ('DOCUMENTS', 'IDs & Documents'), ('KEYS', 'Keys & Access Cards'), ('CLOTHING', 'Clothing & Bags'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=items.models.upload_to)),
                ('resolution_status', models.CharField(choices=[('OPEN', 'Open'), ('SECURED', 'Secured'), ('RETURNED', 'Returned to Owner')], db_index=True, default='OPEN', max_length=20)),
                ('handover_status', models.CharField(blank=True, choices=[('LEFT_AT_LOCATION', 'Left at Location'), ('WITH_FINDER', 'With Finder'), ('SECURITY', 'Handed to Security')], max_length=20, null=True)),
                ('handover_details', models.TextField(blank=True, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='ItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('STATUS_CHANGED', 'Status Changed'), ('RESOLVED', 'Resolved'), ('MATCH_FOUND', 'Match Found'), ('HANDOVER_UPDATED', 'Handover Updated')], max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('from_value', models.CharField(blank=True, max_length=100, null=True)),
                ('to_value', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
