# Generated by Django 5.0.3 on 2026-03-14 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemlog',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='items.item'),
        ),
        migrations.AddField(
            model_name='match',
            name='found_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='items.item'),
        ),
        migrations.AddField(
            model_name='match',
            name='lost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='items.item'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('found_item', 'lost_item')},
        ),
    ]
