# Generated by Django 5.2.12 on 2026-03-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics & Gadgets'), ('DOCUMENTS', 'IDs & Documents'), ('KEYS', 'Keys & Access Cards'), ('CLOTHING', 'Clothing & Bags'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='handover_details',
            field=models.TextField(blank=True, help_text="Specific details (e.g., 'Handed to guard Ramesh at Gate 1')", null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='handover_status',
            field=models.CharField(blank=True, choices=[('LEFT_AT_LOCATION', 'Left at Location'), ('WITH_FINDER', 'With Finder (Me)'), ('SECURITY', 'Handed to Security/Staff'), ('RESOLVED', 'Resolved / Returned to Owner')], max_length=20, null=True),
        ),
    ]
