# Generated by Django 5.2.12 on 2026-03-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_category_item_handover_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='receiver_contact',
            field=models.CharField(blank=True, help_text='Contact number of the receiver', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='receiver_name',
            field=models.CharField(blank=True, help_text='Name of the person who received the item (Security/Staff)', max_length=100, null=True),
        ),
    ]
